name: Awesome List Lint

on:
  push:
  pull_request:

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run awesome-lint
        run: npx --yes awesome-lint
